### ISSUE TITLE
.env parameters enclosed in double quotes get stored with the quotes in SSM

### ISSUE THREAD

**Issue by ilkkapeltola** [kingalban/aws-butler#1]
My situation is that my password has the # sign in it.
And since that starts a comment, at least according to VSCode, I decided I'll wrap it in double quotes

PASSWORD="asohd3#jashf"

but now, when the password is stored in SSM, it has the double quotes in it, which I didn't want.

**Comment by kingalban** [comment]
Previously the env file was read naively, [c1dff289](https://github.com/kingalban/aws-butler/commit/c1dff2891bdb1737ba7f98c3e5109aa5e88701b8) adds `python-dotenv` to handle reading and parsing.

Unfortunately their package doesn't have an easy way to also use the writing/quoting tools without writing directly to a file (or monkeypatching the library), so variables will still be written naively
